CREATE TABLE anonymous_carts (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE anonymous_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anonymous_cart_id UUID NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_anonymous_cart_items_cart FOREIGN KEY (anonymous_cart_id) REFERENCES anonymous_carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_anonymous_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_anonymous_cart_items_cart_product UNIQUE (anonymous_cart_id, product_id)
);

CREATE INDEX idx_anonymous_cart_items_cart_id ON anonymous_cart_items (anonymous_cart_id);
CREATE INDEX idx_anonymous_carts_created_at ON anonymous_carts (created_at);
