CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(19, 2) NOT NULL,
    min_subtotal NUMERIC(19, 2) NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    valid_until TIMESTAMP,
    max_redemptions INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE coupon_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES coupons (id),
    order_id BIGINT NOT NULL REFERENCES orders (id),
    customer_id BIGINT NOT NULL REFERENCES users (id),
    discount_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE orders ADD COLUMN coupon_id BIGINT REFERENCES coupons (id);
ALTER TABLE orders ADD COLUMN discount_amount NUMERIC(19, 2) NOT NULL DEFAULT 0;

CREATE INDEX idx_coupon_redemptions_coupon_id ON coupon_redemptions (coupon_id);
CREATE INDEX idx_coupon_redemptions_customer_id ON coupon_redemptions (customer_id);
